import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider"
import Navbar from "./components/Navbar";
import "./globals.css";
import { Tomorrow } from "next/font/google";

const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${tomorrow.variable} antialiased`}>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar />
            <main className="max-w-2xl mx-auto px-4">
              {children}
            </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
